// This file is generated by rust-protobuf 2.23.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `basic.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_23_0;

#[derive(PartialEq,Clone,Default)]
pub struct BasicMessage {
    // message fields
    pub value1: ::std::string::String,
    pub value2: i32,
    pub value3: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BasicMessage {
    fn default() -> &'a BasicMessage {
        <BasicMessage as ::protobuf::Message>::default_instance()
    }
}

impl BasicMessage {
    pub fn new() -> BasicMessage {
        ::std::default::Default::default()
    }

    // string value1 = 1;


    pub fn get_value1(&self) -> &str {
        &self.value1
    }
    pub fn clear_value1(&mut self) {
        self.value1.clear();
    }

    // Param is passed by value, moved
    pub fn set_value1(&mut self, v: ::std::string::String) {
        self.value1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value1(&mut self) -> &mut ::std::string::String {
        &mut self.value1
    }

    // Take field
    pub fn take_value1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value1, ::std::string::String::new())
    }

    // int32 value2 = 2;


    pub fn get_value2(&self) -> i32 {
        self.value2
    }
    pub fn clear_value2(&mut self) {
        self.value2 = 0;
    }

    // Param is passed by value, moved
    pub fn set_value2(&mut self, v: i32) {
        self.value2 = v;
    }

    // bytes value3 = 3;


    pub fn get_value3(&self) -> &[u8] {
        &self.value3
    }
    pub fn clear_value3(&mut self) {
        self.value3.clear();
    }

    // Param is passed by value, moved
    pub fn set_value3(&mut self, v: ::std::vec::Vec<u8>) {
        self.value3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value3(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value3
    }

    // Take field
    pub fn take_value3(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value3, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for BasicMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value1)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.value2 = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.value1.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.value1);
        }
        if self.value2 != 0 {
            my_size += ::protobuf::rt::value_size(2, self.value2, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value3.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.value3);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.value1.is_empty() {
            os.write_string(1, &self.value1)?;
        }
        if self.value2 != 0 {
            os.write_int32(2, self.value2)?;
        }
        if !self.value3.is_empty() {
            os.write_bytes(3, &self.value3)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BasicMessage {
        BasicMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "value1",
                |m: &BasicMessage| { &m.value1 },
                |m: &mut BasicMessage| { &mut m.value1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "value2",
                |m: &BasicMessage| { &m.value2 },
                |m: &mut BasicMessage| { &mut m.value2 },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "value3",
                |m: &BasicMessage| { &m.value3 },
                |m: &mut BasicMessage| { &mut m.value3 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BasicMessage>(
                "BasicMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BasicMessage {
        static instance: ::protobuf::rt::LazyV2<BasicMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BasicMessage::new)
    }
}

impl ::protobuf::Clear for BasicMessage {
    fn clear(&mut self) {
        self.value1.clear();
        self.value2 = 0;
        self.value3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BasicMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BasicMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct BasicReplyMessage {
    // message fields
    pub value1: ::std::vec::Vec<u8>,
    pub value2: i32,
    pub value3: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BasicReplyMessage {
    fn default() -> &'a BasicReplyMessage {
        <BasicReplyMessage as ::protobuf::Message>::default_instance()
    }
}

impl BasicReplyMessage {
    pub fn new() -> BasicReplyMessage {
        ::std::default::Default::default()
    }

    // bytes value1 = 1;


    pub fn get_value1(&self) -> &[u8] {
        &self.value1
    }
    pub fn clear_value1(&mut self) {
        self.value1.clear();
    }

    // Param is passed by value, moved
    pub fn set_value1(&mut self, v: ::std::vec::Vec<u8>) {
        self.value1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value1(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.value1
    }

    // Take field
    pub fn take_value1(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.value1, ::std::vec::Vec::new())
    }

    // int32 value2 = 2;


    pub fn get_value2(&self) -> i32 {
        self.value2
    }
    pub fn clear_value2(&mut self) {
        self.value2 = 0;
    }

    // Param is passed by value, moved
    pub fn set_value2(&mut self, v: i32) {
        self.value2 = v;
    }

    // string value3 = 3;


    pub fn get_value3(&self) -> &str {
        &self.value3
    }
    pub fn clear_value3(&mut self) {
        self.value3.clear();
    }

    // Param is passed by value, moved
    pub fn set_value3(&mut self, v: ::std::string::String) {
        self.value3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_value3(&mut self) -> &mut ::std::string::String {
        &mut self.value3
    }

    // Take field
    pub fn take_value3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.value3, ::std::string::String::new())
    }
}

impl ::protobuf::Message for BasicReplyMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.value1)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.value2 = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.value3)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.value1.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.value1);
        }
        if self.value2 != 0 {
            my_size += ::protobuf::rt::value_size(2, self.value2, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.value3.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.value3);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.value1.is_empty() {
            os.write_bytes(1, &self.value1)?;
        }
        if self.value2 != 0 {
            os.write_int32(2, self.value2)?;
        }
        if !self.value3.is_empty() {
            os.write_string(3, &self.value3)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BasicReplyMessage {
        BasicReplyMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "value1",
                |m: &BasicReplyMessage| { &m.value1 },
                |m: &mut BasicReplyMessage| { &mut m.value1 },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "value2",
                |m: &BasicReplyMessage| { &m.value2 },
                |m: &mut BasicReplyMessage| { &mut m.value2 },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "value3",
                |m: &BasicReplyMessage| { &m.value3 },
                |m: &mut BasicReplyMessage| { &mut m.value3 },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BasicReplyMessage>(
                "BasicReplyMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BasicReplyMessage {
        static instance: ::protobuf::rt::LazyV2<BasicReplyMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BasicReplyMessage::new)
    }
}

impl ::protobuf::Clear for BasicReplyMessage {
    fn clear(&mut self) {
        self.value1.clear();
        self.value2 = 0;
        self.value3.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BasicReplyMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BasicReplyMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bbasic.proto\"^\n\x0cBasicMessage\x12\x18\n\x06value1\x18\x01\x20\
    \x01(\tR\x06value1B\0\x12\x18\n\x06value2\x18\x02\x20\x01(\x05R\x06value\
    2B\0\x12\x18\n\x06value3\x18\x03\x20\x01(\x0cR\x06value3B\0:\0\"c\n\x11B\
    asicReplyMessage\x12\x18\n\x06value1\x18\x01\x20\x01(\x0cR\x06value1B\0\
    \x12\x18\n\x06value2\x18\x02\x20\x01(\x05R\x06value2B\0\x12\x18\n\x06val\
    ue3\x18\x03\x20\x01(\tR\x06value3B\0:\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
